site_name: Open Ireland Testbed
site_url: https://open-ireland-testbed.github.io/wiki/
theme:
  name: material
  logo: images/logo.svg                    # put under docs/images/
  favicon: images/favicon.png              # 32×32 or 48×48
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
  palette:
    - scheme: default                      # light
      primary: indigo
      accent: blue
    - scheme: slate                        # dark
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra:
  social:
    - icon: material/github
      link: https://github.com/open-ireland-testbed/wiki

repo_url: https://github.com/open-ireland-testbed/wiki
edit_uri: ""                               # hide “Edit on GitHub” (optional)
copyright: "© 2025 Open Ireland Testbed"
nav:
  []
